algorand/conduit

conduit/plugins/exporters/postgresql/postgresql_exporter.go, conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
If the postgresql exporter is given a block without a ledger state delta object, the error message gave no indication about what the user should do. Attempt to clarify the situation by telling the user to check that their algod importer is in follower mode.
Update existing unit test.
=> errors(postgresql): Clarify missing ledger state delta message.

conduit/plugins/processors/filterprocessor/fields/searcher.go, conduit/plugins/processors/filterprocessor/gen/generate.go
tag is one of the config field for filter processor. It would be convenient to have a list of supported tags in the conduit docs.  
the doc would have a table like this, 
|filter tag|transaction field|
| -------- | ------- |
|aca|ApplyData.AssetClosingAmount|
|apid|ApplyData.ApplicationID|
|ca|ApplyData.ClosingAmount|
|caid|ApplyData.ConfigAsset|
|lsig.msig.thr|SignedTxn.Lsig.Msig.Threshold|
|lsig.msig.v|SignedTxn.Lsig.Msig.Version|
|msig.thr|SignedTxn.Msig.Threshold|
|msig.v|SignedTxn.Msig.Version|
|rc|ApplyData.CloseRewards|
|rr|ApplyData.ReceiverRewards|
|...||
=> conduit-docs: conduit_processors_filter_tags.md

conduit/plugins/importers/algod/algod_importer.go
removing a comment that isn't relevant anymore.
=> importer: remove a comment

cmd/conduit/internal/list/list.go, cmd/conduit/main.go, cmd/conduit/main_test.go, conduit/config.go, conduit/pipeline/pipeline.go, conduit/pipeline/pipeline_test.go
If an invalid log level is detected print the valid ones.
If the data directory is not set print a message saying that it is required by CLI or environment variable.
More descriptive cobra documentation strings.
Simplify error reporting by printing them if they are returned.
New and existing unit tests.
=> usability: Better error messages and documentation.

.github/workflows/goreleaser.yml, .goreleaser.yaml, Makefile, cmd/conduit/main.go, version/strings.go
Enable goreleaser for building and publishing conduit binaries.
The automation triggers whenever a tag starting with `v1.` is pushed.
The previous versioning and deployment stuff seemed really complicated, and I'm really not sure what it was adding. Please let me know if this smaller process is missing any important functionality that needs to be added back.
I pushed a tag to my fork:
* [The action ran.](https://github.com/winder/conduit/actions/runs/4432232042)
* [A release was published. ](https://github.com/winder/conduit/releases/tag/v1.0.0)
The downloaded binary looks good:
```
$ ./conduit -v
Conduit 1.0.0 (c8262a5)
```
=> release: Goreleaser configuration and automation.

.github/workflows/goreleaser.yml, .goreleaser.yaml, Dockerfile, docs/Docker.md
Add a docker multi-arch build + deployment configuration.
~For now the docker hub deployment is disabled.~ **Hyperflow has added credentials to the repo so that the container can  be deployed.**
Goreleaser provides binaries from the build step to the Dockerfile to ensure containers have the same files as the archives.
Tested with `goreleaser release --skip-publish --snapshot --clean`
The files are here:
```
~$ docker images|grep conduit
algorand/conduit   1.0.1-next-amd64   0863fc121046   About a minute ago   96.9MB
algorand/conduit   latest-amd64       0863fc121046   About a minute ago   96.9MB
algorand/conduit   1.0.1-next-arm64   907990ee4310   About a minute ago   90.5MB
algorand/conduit   latest-arm64       907990ee4310   About a minute ago   90.5MB
```
The architecture appears as …
=> docker: Add docker to the release pipeline

.github/workflows/goreleaser.yml, .goreleaser.yaml, Dockerfile, docker/docker-entrypoint.sh, docs/Docker.md, go.sum
This adds a number of small improvements over the first pass container:
* Enable the docker release.
* Better data dir / user permissions, [similar to #5276](https://github.com/algorand/go-algorand/pull/5276).
* Move data dir from `/conduit/data` to `/data`.
* Install `ca-certificates` to allow using an algod provider service.
Similar to the previous docker PR: https://github.com/algorand/conduit/pull/50
Additional testing:
Mount data directory:
```
docker run -it --rm -v $(pwd)/local_data_dir:/data algorand/conduit:latest-snapshot-amd64
```
Check `CMD` overrides:
```
docker run -it --rm -v $(pwd)/local_data_dir:/data algorand/conduit:latest-snapshot-amd64 -h
docker run -it --rm -v $(pwd)/local_data_dir:/data algorand/conduit:latest-snapshot-amd64 init
docker run -it --rm -v …
```
=> docker: data dir & user permissions, install ca-certificates, better data dir location, more.

.github/workflows/docs-pr.yml
In https://github.com/algorand/conduit/pull/59 I forgot to include the repo directory, so the new plugin docs were not found.
=> docs: add missing repo directory.

README.md, conduit/plugins/importers/algod/README.md, conduit/plugins/importers/algod/algod_importer.go, conduit/plugins/importers/algod/algod_importer_config.go, conduit/plugins/importers/algod/algod_importer_test.go, conduit/plugins/importers/algod/mock_algod_test.go, conduit/plugins/importers/algod/sample.yaml, docs/tutorials/IndexerMigration.md, docs/tutorials/IndexerWriter.md
Adds a new option to automatically lookup an appropriate catchpoint label during startup.
New unit tests.
Manually run conduit with `-r 27000001` to see that the correct catchpoint label is automatically populated.
=> algod importer: Auto catchpoint label lookup.

cmd/conduit/main.go, conduit/plugins/exporters/exporter_factory.go, conduit/plugins/exporters/exporter_factory_test.go, conduit/plugins/exporters/noop/noop_exporter_test.go, conduit/plugins/importers/algod/algod_importer.go, conduit/plugins/importers/importer_factory.go, conduit/plugins/importers/importer_factory_test.go, conduit/plugins/processors/processor_factory.go, conduit/plugins/processors/processor_factory_test.go, go.mod, pkg/cli/cli.go
Proposing that when `Register()` is called twice for the same plugin name, it will panic.
An alternative would involve changing the signature to return an `error`.
This is mostly about familiarizing myself with the Conduit repo. This is not an urgent issue.
As I was playing around with conduit [plugin templates](https://github.com/algorand/conduit-plugin-template) I realized there is a slight issue with plugin registration. 
> It's possible to register a plugin with the same name as another, and overwrite the first registration
The current functionality keeps a map from a user provided name to the actual plugin. If a plugin with the same name as another is registed a second time, it simply overwrites the first. This certainly isn't a pressing concern as we have complete control over what …
=> enhancement: disallow Register() name dupes

conduit/plugins/importers/algod/algod_importer.go, conduit/plugins/importers/algod/algod_importer_test.go, conduit/plugins/importers/algod/mock_algod_test.go
The catchup logic was too aggressive. It should not run unless it's needed. With this change the target block / state delta are queried. If they are available the catchup phase is skipped.
Update unit tests.
=> algod importer: check if node needs catchup.

conduit/plugins/processors/filterprocessor/gen/generate.go, go.mod, go.sum
This PR results from fixing the type inconsistency for `EvalDelta` in `go-algorand-sdk` (https://github.com/algorand/go-algorand-sdk/pull/531) and passing the [failing nightly test in indexer](https://app.circleci.com/pipelines/github/algorand/indexer/3796/workflows/4016c18f-f298-443e-a887-8cc7dce246f7/jobs/5337).
This should not be merged until https://github.com/algorand/go-algorand-sdk/pull/531 is merged and the `go.mod` in this project is updated.
=> bugfix: indexer import types

conduit/plugins/importers/algod/algod_importer.go, conduit/plugins/importers/algod/algod_importer_test.go
Don't attempt to query deltas from a follower node for round 0. Instead, just declare that we need to catch up and log:
> No state deltas are ever available for round 0
CI - introduced new unit test cases
=> Bug-Fix: don't attempt to get deltas at round 0

conduit/pipeline/pipeline.go, conduit/plugins/importers/algod/algod_importer.go
In preparing the bugfix in https://github.com/algorand/go-algorand/pull/5449, I discovered that conduit's logger wasn't printing out at the log-level that I was expecting (TRACE). I made some minor fixes to address this problem and also added the traces that I found helpful. Finally, a couple of logs were missing the received error from algod, so I added these.
CI + local testing
=> bug-fix: better configuration of plugin loggers + trace all algod requests

conduit/plugins/processors/filterprocessor/README.md, conduit/plugins/processors/filterprocessor/config.go, conduit/plugins/processors/filterprocessor/sample.yaml, docs/tutorials/WritingBlocksToFile.md
The equal and exact types were merged in https://github.com/algorand/indexer/pull/1468 but the documentation was not properly updated. This PR updates the documentation to replace `exact` with `equal`.
=> docs: fix filter docs to replace exact.

.goreleaser.yaml
These changes make it easier to borrow the goreleaser configuration for child projects.
* A single environment variable names the docker images.
* The LDFlags and binary definitions are grouped together.
Manually running goreleaser.
=> Generalize goreleaser config.

docs/Docker.md
Fixes typo on Docker documentation. The entry point is using `cp /etc/algorand/conduit.yml /data/conduit.yml` and the documentation refers to `config.yml`
I didn't test the changes, I think they can be validated by inspection.
=> Fix typo on conduit configuration file

go.mod, go.sum
Update to the latest go-codec and go-algorand-sdk dependencies.
CI.
=> Update go-codec and go-algorand-sdk dependencies.

conduit/pipeline/pipeline.go, conduit/pipeline/pipeline_test.go
Update metrics to consider inner transactions.
New unit test.
=> Update metrics to include inner transactions.

.github/workflows/tests.yml, Makefile
Moves the CI_E2E_FILENAME definition into the Makefile so that `make e2e-conduit` is easier to run locally.
This PR also pins the filename to a more recent version.
The variable is defined with `?=` to allow it to be overridden by an environment variable.
Existing CI.
=> Define and update e2e file in Makefile.

conduit/plugins/importers/algod/algod_importer.go, conduit/plugins/importers/algod/algod_importer_test.go, conduit/plugins/importers/algod/mock_algod_test.go
If algod is restarted after it receives a sync round update but before it fetches the new round(s), then the algod follower and conduit will stall. Conduit will keep waiting for algod to reach the new sync round but it never happens.
This change adds some extra logic to the `WaitForBlock` call. If there is a timeout or a bad response, a new attempt to set the sync round is made.
This PR also removes the retry loop from the algod importer. Retry is now managed by the pipeline.
Update existing unit tests.
=> algod importer: Update sync on WaitForBlock error.

conduit/data/config.go, conduit/loggers/loggers.go, conduit/pipeline/logging.go, conduit/pipeline/logging_test.go
Change Conduit's formatter for a higher level of granularity to:
```go
time.RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
```
> The RFC3339Nano format removes trailing zeros from the seconds field and thus may not sort correctly once formatted.
Taken from: https://pkg.go.dev/time
CI
=> more granular timestamps in logs

conduit/plugins/importers/algod/algod_importer.go, conduit/plugins/importers/algod/algod_importer_test.go, conduit/plugins/importers/algod/mock_algod_test.go
1. changing the amount of time to wait for the next round
2. adding more context to the `SyncError` type
During a recent EC2 import test, I noticed that after catching up, around 1% of imports are reporting an error/warning:
```json
{
"__type":"importer",
"_name":"algod",
"level":"warning",
"msg":"Sync error detected, attempting to set the sync round to recover the node: wrong round returned from status for round: 0 != 31117945",
"time":"2023-08-07T15:31:16.166545875Z"
}
{
"__type":"Conduit",
"_name":"main",
"level":"error",
"msg":"wrong round returned from status for round: 0 != 31117945",
"time":"2023-08-07T15:31:16.166783576Z"
}
```
The `pipelining` branch, which added some more information to the `SyncError` errored similarly with the warning msg:
```txt
importer algod.GetBlock() sync …
```
=> Algod Importer: Longer Timeout

README.md, conduit/plugins/exporters/filewriter/README.md, conduit/plugins/exporters/filewriter/sample.yaml
Remove quotes to make the documentation more consistent.
N/A
=> Remove quotes in file_write examples.

.goreleaser.yaml
Add the version to release filenames to be closer to the pattern used by algod.
conduit_Darwin_all_1.3.1.tar.gz
conduit_Linux_arm64_1.3.1.tar.gz
conduit_Linux_x86_64_1.3.1.tar.gz
conduit_Windows_arm64_1.3.1.tar.gz
conduit_Windows_x86_64_1.3.1.tar.gz
Run goreleaser locally.
=> build: add version to release filename.

api/api.go, api/api_test.go, conduit/data/config.go, conduit/pipeline/pipeline.go, pkg/cli/cli.go, pkg/cli/internal/initialize/conduit.yml.example
Add a new option for an API which includes a health endpoint to return the current round.
[Demo and overview.](https://www.youtube.com/watch?v=wDRf_haonUk)
New unit tests.
=> api: New API with health endpoint

docs/ExternalPlugins.md
Add a reference to CockroachDB exporter.
=> docs: add reference to external plugin

.goreleaser.yaml
Update release notes:
* create as a draft.
* add header and footer.
=> Update goreleaser release notes.

.goreleaser.yaml
There were two issues with the new release template:
* missing forward slash in the diff URL.
* The triple-dash separator turned the changelog into a header, which was not intentional.
=> ci: fix release notes template formatting.

.github/workflows/goreleaser.yml, .goreleaser.yaml
Sign checksum file as part of publishing a release.
The approach here follows a suggestion in the goreleaser docs where the signature is limited to the checksum file.
References:
* goreleaser docs: https://goreleaser.com/customization/sign/
* ghaction-import-gpg docs: https://github.com/crazy-max/ghaction-import-gpg
Repository configuration requires adding the GPG secret and passphrase.
Tested the configuration in a private repo:
https://github.com/algorand/goreleaser-test/releases/tag/untagged-e548c44def7b11988fec
=> ci: Add gpg signature to checksum file.

conduit/plugins/processors/filterprocessor/filter_processor_bench_test.go
Add new benchmarks Benchmarks for filters.
The results suggest that we're doing something extremely inefficient when setting up each additional filter.
Applying one filter to 1 or 25000 transactions has an almost negligible difference.
On the other hand there seems to be a fixed 8ms overhead for each filter.
The numbers in each report are as follows:
* number of transactions in the test block
* number of string equality filters
* number of regex filters
* number of numeric filters.
| num txn | eq filters | regex filters | numeric filters |
| ------------ | --------- | ---------- | ------------|
| 25000| 1000 | 0 | 0 |
| 1| 1000 | 0 | 0 |
| 25000| 1 | 0 | 0 |
| 1| 1 | 0 | 0 |
| 25000| 0|1000 | 0 |
| 1| 0|1000 | 0 |
| 25000| 0|1  | 0 |
| 1| 0|1  | 0 |
| 25000| 0|0|1000 | 
| 1| 0|0|1000 | 
| …
=> Filter Processor Benchmarking

README.md
Add system requirements section to README.
N/A
=> Add system requirements to README.

go.mod, go.sum
Bump go-algorand-sdk dependency to v2.4.0 to support v39 consensus protocol.
=> Consensus: v39 protocol support via go-algorand-sdk

go.mod, go.sum
Bump to indexer v3.4.1-rc1 and go-algorand-sdk 2.4.0
=> Versions: Bump to indexer v3.4.1-rc1 and go-algorand-sdk 2.4.0

go.mod, go.sum
Bump indexer dependency to v3.4.0 (essentially the same as RC1 save for a read side patch).
Existing Tests Pass.
=> Dependency: Bump indexer dependency to v3.4.0

.github/workflows/reviewdog.yml
Bump go version for workflows to 1.20.14.
Existing tests and builds should succeed.
=> Bump go version for workflows to 1.20.14

conduit/plugins/importers/algod/algod_importer.go, conduit/plugins/importers/algod/algod_importer_test.go
https://github.com/algorand/go-algorand/issues/5352 has been fixed by https://github.com/algorand/go-algorand/pull/5798, and this PR undoes the workaround needed because of the original issue.
The original issue was that, if algod does fast catchup to round `X`, algod's REST API could not serve block `X`, since fast catchup did not also include block certificates. To work around this, conduit had to limit catchpoints to rounds `< X`, but now with this fixed in algod, the catchpoint round can be `<= X`.
New unit test cases added
=> Allow catchpoints from the exact target round

go.mod, go.sum
Bump go sdk to 2.6 and indexer to latest main commit.
=> Dependencies: Bump go sdk to 2.6 and indexer to latest main commit

README.md, conduit/plugins/processors/filterprocessor/filter_processor_test.go, conduit/plugins/processors/filterprocessor/gen/generate.go, go.mod, go.sum
Support v40 consensus version and new heartbeat transaction type.
=> Incentives: Bump to v40 consensus supporting development versions of Go SDK and Indexer.

go.mod, go.sum
Stable versions of go-algorand-sdk (v2.11.0) and indexer (v3.9.0).
=> Deps: Stable versions of go-algorand-sdk (v2.11.0) and indexer (v3.9.0).
